# This is a basic workflow to help you get started with Actions

name: CD - Tag&Release

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    tags:
      - '*'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: build_release
    permissions: write-all
    # The type of runner that the job will run on
    runs-on: labview2023-win10
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        
      # Print current local direcotry used for release process and set a dummy version file from tag
      - name: Create ${{ github.ref_name }}.buildversion
        run: |
          echo PWD "$pwd"
          type nul > "$pwd/source/PreBuild/${{ github.ref_name }}.buildversion"
        
      # Set LabVIEW Build spec version from dummy version file
      - name: LabVIEW build spec ver update
        run: LabVIEWCLI -OperationName RunVI -VIPath "$pwd\source\PreBuild\RunCL - Set Version Info.vi" "$pwd\source\LV_Calculator.lvproj" "LV_Calculator" "My Computer"
        
      # Get Executable Version Information
      - name: version
        run: echo "::set-output name=version::v1.0.1"
        id: version
      
      # Build LabVIEW Executable via LabVIEWCLI
      - name: LabVIEW build
        run: LabVIEWCLI -LogToConsole true -OperationName ExecuteBuildSpec -ProjectPath "$pwd\source\LV_Calculator.lvproj" -BuildSpecName "LV_Calculator" -LabVIEWPath "C:\Program Files (x86)\National Instruments\LabVIEW 2023\LabVIEW.exe" -PortNumber 3363
      
      # Create GitHub Release  
      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ github.ref_name }}
          tag_name: ${{ github.ref }}
          body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ github.token }}
          
      # Upload Executable to GitHub Release
      - name: upload build artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./builds/LV_Calculator/LV_Calculator/LV_Calculator.exe
          asset_name: LV_Calculator.exe
          asset_content_type: application/exe
